# Generated by Django 4.2.7 on 2023-11-10 16:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_remove_user_comment_remove_user_name_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='user',
            options={'verbose_name': 'пользователь', 'verbose_name_plural': 'пользователи'},
        ),
        migrations.AlterField(
            model_name='user',
            name='token',
            field=models.CharField(default='24756212749553475', max_length=100, verbose_name='token'),
        ),
    ]
